name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "test/layer-cache"

jobs:
  test:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      # -----------------------------------------------------------------------
      # Github Actions does not support Docker layer caching out of the box.
      # This means every build will be 7+ minutes unless we cache things.
      #
      # We'll be using a 3rd party action to handle caching Docker layers.
      #
      # It's also recommended to pull images you need before caching since it
      # ends up being faster than reading from the cache.
      - name: "Pull required official Docker images before we cache layers"
        run: |
          cp --no-clobber .env.example .env
          docker-compose pull postgres redis
      - uses: "satackey/action-docker-layer-caching@v0.0.11"
        continue-on-error: true
      # -----------------------------------------------------------------------

      - name: "Test"
        run: |
          # Remove volumes in CI to avoid permission errors due to UID / GID.
          sed -i "s|.:/app|/tmp:/tmp|g" .env*
          sed -i "s|.:/app|/tmp:/tmp|g" docker-compose.override.yml.example

          ./run ci:test
        env:
          DOCKER_BUILDKIT: "1"
